-- Creates the integration delta table.
-- Replace `your_project` with your actual GCP project ID.

CREATE TABLE IF NOT EXISTS `your_project.crm_integration.hubspot_updates`
(
  -- Surrogate key for this integration row (UUID generated by source pipeline)
  row_id                  STRING    NOT NULL,

  -- HubSpot object targeting
  object_type             STRING    NOT NULL,   -- 'contacts' | 'companies' | 'deals'
  hubspot_id              STRING,               -- HubSpot internal object ID
  business_key            STRING,               -- fallback identifier value (e.g. email)
  business_key_property   STRING,               -- HubSpot property name for the key above

  -- Properties payload — stored as JSON to avoid schema churn when fields expand
  -- Shape: {"bq_email": "x@y.com", "bq_mrr": 1200, ...}
  properties              JSON      NOT NULL,

  -- Source timestamps
  last_changed_at         TIMESTAMP NOT NULL,   -- when the source record last changed
  sync_attempted_at       TIMESTAMP,            -- last time sync was tried
  sync_succeeded_at       TIMESTAMP,            -- last time sync succeeded

  -- Integration state machine: PENDING → IN_PROGRESS → SUCCESS | FAILED
  sync_status             STRING    NOT NULL    DEFAULT 'PENDING',
  sync_error              STRING,               -- truncated HubSpot error on failure
  retry_count             INT64     NOT NULL    DEFAULT 0
)
PARTITION BY DATE(last_changed_at)
CLUSTER BY object_type, sync_status
OPTIONS (
  description = 'Delta table for BigQuery → HubSpot CRM sync. Source of truth for pending/failed updates.',
  require_partition_filter = FALSE
);
